const teamInfo = [
  {
    name: "Akshit Verma",
    role: "Junior & Creative Member",
    fb: "https://www.facebook.com/profile.php?id=100057273051263",
    insta: "https://www.instagram.com/ronnie.3784/",
    linkedin: "https://www.linkedin.com/in/akshit-verma-205aa5219/",
    github: "https://github.com/vakshit",
  },
  {
    name: "B.Anshuman",
    role: "Junior Member",
    fb: "https://www.facebook.com/b.anshuman1305",
    insta: "https://www.instagram.com/human_b.a/",
    linkedin: "https://www.linkedin.com/in/b-anshuman13/",
    github: "https://github.com/ba-13",
  },
  {
    name: "Pratyush Gupta",
    role: "Junior Member",
    fb: "https://www.facebook.com/pratyush.gupta.39566/",
    insta: "https://www.instagram.com/pratyush.gupta.39566/",
    linkedin: "https://www.linkedin.com/in/pratyush-gupta-60858521b/",
    github: "https://github.com/PratyushGupta0",
  },

  {
    name: "Aryan Jain",
    role: "Junior Member",
    fb: "https://www.facebook.com/profile.php?id=100056025635847",
    insta: "https://www.instagram.com/jain_aryan_19/",
    linkedin: "https://www.linkedin.com/in/aryan-jain-1908/",
    github: "https://github.com/aryanjain19",
  },
  {
    name: "Saransh Shivhare",
    role: "Junior Member",
    fb: "https://www.facebook.com/profile.php?id=100006630047839",
    insta: "https://www.instagram.com/saransh_shivhare/",
    linkedin: "https://www.linkedin.com/in/saransh-shivhare-4b02ba200/",
    github: "https://github.com/saranshg20",
  },

  {
    name: "Rahul Rustagi",
    role: "Junior Member",
    fb: "https://www.facebook.com/profile.php?id=100002427998692",
    insta: "https://www.instagram.com/me_be_rahul/",
    linkedin: "https://www.linkedin.com/in/rahul-rustagi-34254321b/",
    github: "https://github.com/rrustagi20",
  },
  {
    name: "Adit Jain",
    role: "Junior Member",
    fb: "https://www.facebook.com/adit.jain.1675/",
    insta: "https://www.instagram.com/jadit_19/",
    linkedin: "https://www.linkedin.com/in/adit-jain-658481b9/",
    github: "https://github.com/Jadit19",
  },
  {
    name: "Rajarshi Dutta",
    role: "Junior Member",
    fb: "https://www.facebook.com/rajarshi.dutta.507",
    insta: "https://www.instagram.com/rajarshi.dutta.507/?hl=en",
    linkedin: "https://www.linkedin.com/in/rajarshi-dutta-1074941ba/",
    github: "https://github.com/Rajarshi1001",
  },
  {
    name: "Sharath Kumar V",
    role: "Junior Member",
    fb: "https://www.facebook.com/sharath.kumarv.39/",
    insta: "https://www.instagram.com/sharath_0313/",
    linkedin: "https://www.linkedin.com/in/sharath-kumar-v-bb907421b/",
    github: "https://github.com/Sharath0313",
  },

  {
    name: "Ujwal Jyot Panda",
    role: "Junior Member",
    fb: "https://www.facebook.com/ujwaljyot.panda.9/",
    insta: "https://www.instagram.com/ujwal.j.p/",
    linkedin: "#",
    github: "https://github.com/ujwaljp",
  },
  {
    name: "Aditya Anand",
    role: "Junior Member",
    fb: "https://www.facebook.com/adityaanandaa28",
    insta: "https://www.instagram.com/adityaanand28/",
    linkedin: "https://www.linkedin.com/in/adityaanand28",
    github: "https://github.com/adityaanand28",
  },
  {
    name: "Atharva Dehadraya",
    role: "Junior Member",
    fb: "https://www.facebook.com/atharva.dehadraya",
    insta: "#",
    linkedin: "https://www.linkedin.com/in/atharvadehadraya",
    github: "https://github.com/QuantuMAtharva",
  },
  {
    name: "Batta Soumith",
    role: "Junior Member",
    fb: "https://www.facebook.com/soumith.monu",
    insta: "https://www.instagram.com/s0umith/",
    linkedin: "https://www.linkedin.com/in/soumith-chowdary",
    github: "https://github.com/s0umith",
  },
  {
    name: "Rakshit Yash ",
    role: "Junior Member",
    fb: "https://www.facebook.com/rakshit.yash.142",
    insta: "https://www.instagram.com/rxk_shit/",
    linkedin: "https://www.linkedin.com/in/rakshit-yash-83a45b214/",
    github: "https://github.com/RakshitYash",
  },
  {
    name: "L Gokulnath",
    role: "Junior Member",
    fb: "https://www.facebook.com/gokulnath.l.75/",
    insta: "#",
    linkedin: "#",
    github: "https://github.com/lgokulnath",
  },
  {
    name: "Aryaman Badkul",
    role: "Junior Member",
    fb: "https://www.facebook.com/aryaman.badkul/",
    insta: "https://www.instagram.com/r_a_mann/",
    linkedin: "https://www.linkedin.com/in/aryaman-badkul-755373204/",
    github: "https://github.com/aryaman-a-student",
  },
  {
    name: "Karan Jeyasankar",
    role: "Junior Member",
    fb: "https://www.facebook.com/karan.jey.37/",
    insta: "https://www.linkedin.com/in/karan_jey_",
    linkedin: "https://www.linkedin.com/in/karan-jeyasankar-98135595/",
    github: "karan-jey",
  },
  {
    name: "Aryan Sharma",
    role: "Junior Member",
    fb: "https://www.facebook.com/profile.php?id=100056630960019",
    insta: "https://www.instagram.com/aryan_shrama123",
    linkedin: "www.linkedin.com/in/aryan-sharma-540338215",
    github: "https://github.com/aryans-20",
  },
  {
    name: "Sujal Harkut",
    role: "Junior Member",
    fb: "https://www.facebook.com/sujalharkut",
    insta: "https://www.instagram.com/sujal_harkut/",
    linkedin: "https://www.linkedin.com/in/sujal-harkut-8027601b9/",
    github: "https://github.com/sujalharkut",
  },
  {
    name: "Dev Barbhaya",
    role: "Junior Member",
    fb: "https://www.facebook.com/dev.barbhaya.18/",
    insta: "https://www.instagram.com/devbarbedwire/",
    linkedin: "https://www.linkedin.com/in/dev-barbhaya-32a09b210/",
    github: "https://github.com/xDB-9",
  },
  {
    name: "Jaya Gupta",
    role: "Junior Member",
    fb: "https://www.facebook.com/27JayaGupta",
    insta: "https://www.instagram.com/jayagupta_27/",
    linkedin: "https://www.linkedin.com/in/jaya-gupta-78a7b7205/",
    github: "https://github.com/27-JayaGupta",
  },
  {
    name: "Arth Banka",
    role: "Junior Member",
    fb: "https://www.facebook.com/arth.banka/",
    insta: "https://www.instagram.com/arth_banka/",
    linkedin: "https://www.linkedin.com/in/arth-b-6a083a125/",
    github: "https://github.com/Arth-DEVOPS",
  },
  {
    name: "Subhrajit Mishra",
    role: "Junior Member",
    fb: "https://www.facebook.com/subhrajit.mishra.37017",
    insta: "https://www.instagram.com/subhrajit.mishra.101/",
    linkedin: "http://www.linkedin.com/in/subhrajit-mishra-a0b851210",
    github: "https://github.com/subhrajitm20",
  },
  {
    name: "Gagan Sipani",
    role: "Junior Member",
    fb: "https://www.facebook.com/gagan.sipani.9",
    insta: "#",
    linkedin: "https://www.linkedin.com/in/gagan-sipani-431859153",
    github: "https://github.com/gagans20",
  },
  {
    name: "Juee",
    role: "Junior Member",
    fb: "#",
    insta: "#",
    linkedin: "#",
    github: "#",
  },
];

const element = document.getElementById("y20");

teamInfo.forEach((member) => {
  const div = document.createElement("div");
  div.classList.add("col-md-6");
  div.classList.add("col-lg-4");
  div.innerHTML = `<div class="team-minimal"><div class="team-minimal-figure"><img src="images/team/y20/${member.name}.jpg" alt="" width="370" height="395" style="width:370px; height:460px; object-fit: fill;" /><ul class="team-minimal-soc-list"><li><a class="icon icon-lg fa-facebook" href="${member.fb}"></a></li><li><a class="icon icon-lg fa-instagram" href="${member.insta}"></a></li><li><a class="icon icon-lg fa-linkedin" href="${member.linkedin}"></a></li></ul></div><div class="team-minimal-caption"><h4><a class="team-name"><spanstyle="font-family:Rajdhani;letter-spacing:-34;font-weight:bolder;">${member.name}</span></a></h4><p style="font-family:'SF UI Display Light';">${member.role}</p></div></div>`;
  element.appendChild(div);
});
